;;; config-require.el ---

;; Copyright (C) 2014 Grégoire Jadi
;; Author: Grégoire Jadi <gregoire.jadi@gmail.com>
;; This program is free software: you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation, either version 3 of
;; the License, or (at your option) any later version.
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
;;; Commentary:
;;; Code:

(require 'saveplace)
(require 'ffap)
(require 'uniquify)
(require 'ansi-color)
(require 'recentf)
(require 'verbiste)
(require 'info)
(require 'ebib)
(require 'key-chord)
(require 'graze-url nil t)
(require 'compile-cache)
(require 'dired)
(require 'comint)
(require 'doc-view)
(require 'hideshow)
(require 'gtk-lookup)
(require 'semantic)
(require 'semantic/ia)
(require 'semantic/bovine/gcc)
(require 'semantic/imenu)
(require 'cedet-global)
(require 'company)
(require 'company-yasnippet)
(require 'http-post-simple)
(require 'thingatpt)
(require 'imenu)
(require 'bytecomp)
(require 'el-dispatcher)
(require 'doctags)
(require 'ediff)
(require 'emms-setup)
(require 'emms-player-mplayer-quiet)
(require 'magit)
(require 'magit-svn)
(require 'magit-blame)
(require 'magit-stgit)
(require 'gtags)
(require 'tidy-autoloads)
(require 'rcirc)
(require 'shoes-off-log)
(require 'shoes-off)
(require 'cc-mode)
(require 'javadoc-lookup)
(require 'maven-fetch)
(require 'eclim)
(require 'eclimd)
(require 'config-company)
(require 'company-emacs-eclim)
(require 'js2-mode)
(require 'moz)
(require 'xlicense)
(require 'skeleton)
(require 'elisp-slime-nav)
(require 'redshank-loader)
(require 'markdown-mode)
(require 'workgroups)
(require 'scratch)
(require 'undo-tree)
(require 'linum)
(require 'ido)
(require 'ido-ubiquitous)
(require' fic-ext-mode)
(require 'markit)
(require 'yaml-mode)
(require 'dired-x)
(require 'rainbow-mode)
(require 'chm-view)
(require 'cursor-chg)
(require 'woman)
(require 'browse-kill-ring)
(require 'manual-tagging)
(require 'w3m-wget)
(require 'smart-tab)
(require 'edebug)
(require 'compilation-font)
(require 'parallel)
(require 'ess)
(require 'ess-site)
(require 'adaptive-wrap)
(require 'multiple-cursors)
(require 'multi-term)
(require 'tuareg)
(require 'ocamldebug)
(require 'org)
(require 'ox-latex)
(require 'ox-beamer)
(require 'ox-md)
(require 'ox-reveal)
(require 'org-list)
(require 'org-drill)
(require 'org-ebib)
(require 'ob-asymptote)
(require 'ob-awk)
(require 'ob-calc)
(require 'ob-C)
(require 'ob-clojure)
(require 'ob-css)
(require 'ob-ditaa)
(require 'ob-dot)
(require 'ob-emacs-lisp)
(require 'ob-gnuplot)
(require 'ob-haskell)
(require 'ob-java)
(require 'ob-js)
(require 'ob-latex)
(require 'ob-ledger)
(require 'ob-lisp)
(require 'ob-lilypond)
(require 'ob-matlab)
(require 'ob-mscgen)
(require 'ob-ocaml)
(require 'ob-octave)
(require 'ob-org)
(require 'ob-perl)
(require 'ob-python)
(require 'ob-R)
(require 'ob-ruby)
(require 'ob-sass)
(require 'ob-scheme)
(require 'ob-screen)
(require 'ob-sh)
(require 'ob-sql)
(require 'ob-sqlite)
(require 'calendar)
(require 'diary-lib)
(require 'org-annotate-file)
(require 'os)
(require 'os-bb)
(require 'os-github)
(require 'os-rmine)
(require 'org-contacts)
(require 'org-magit)
(require 'plantuml-mode)
(require 'ob-plantuml)
(require 'projectile)
(require 'ag)
(require 'prolog)
(require 'ediprolog)
(require 'view)
(require 'rust-mode)
(require 'scala-mode-auto)
(require 'ensime)
(require 'color-moccur)
(require 'moccur-edit)
(require 'slime-autoloads)
(require 'slime)
(require 'info-look)
(require 'smartparens)
(require 'smartparens-config)
(require 'latex)
(require 'preview)
(require 'w3m-load)
(require 'w3m)
(require 'w3m-search)
(require 'browse-url)
(require 'xmlgen)
(require 'sgml-mode)
(require 'sxml<->xml)
(require 'xwidget nil t)
(require 'parallel-xwidget)
(require 'yasnippet)

(provide 'config-require)
;;; config-require.el ends here
