(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-c m") 'helm-M-x)
(global-set-key (kbd "C-c C-m") 'helm-M-x)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "C-x b") 'helm-buffers-list)
(global-set-key (kbd "C-c h") 'helm-command-prefix)
(global-set-key (kbd "C-c j") 'helm-pages)
(helm-mode 1)
